# Generated by Django 3.2.5 on 2021-08-01 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='create_time',
            new_name='create_on',
        ),
        migrations.RenameField(
            model_name='quote',
            old_name='creator',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='quoteitem',
            old_name='quantity',
            new_name='qty',
        ),
        migrations.AlterField(
            model_name='quoteitem',
            name='price',
            field=models.IntegerField(default=0, verbose_name='قیمت'),
        ),
    ]
