# Generated by Django 3.2.5 on 2021-08-02 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        ('quote', '0002_auto_20210801_1105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='quoteitem',
            name='price',
        ),
        migrations.AddField(
            model_name='quoteitem',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='organization.organization', verbose_name='سازمان'),
            preserve_default=False,
        ),
    ]
