# Generated by Django 3.2.5 on 2021-08-02 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0003_auto_20210802_0750'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoteitem',
            name='pricee',
            field=models.IntegerField(default=0, verbose_name='قیمت'),
        ),
    ]
