# Generated by Django 3.2.5 on 2021-08-03 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0004_quoteitem_pricee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quoteitem',
            name='organization',
        ),
    ]
