# Generated by Django 3.2.5 on 2021-08-05 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_pdf'),
        ('organization', '0001_initial'),
        ('quote', '0006_quote_organization'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quote',
            options={'permissions': [], 'verbose_name': 'پیش فاکتور', 'verbose_name_plural': 'پیش فاکتورها'},
        ),
        migrations.AlterModelOptions(
            name='quoteitem',
            options={'permissions': [], 'verbose_name': ' ایتم پیش فاکتور', 'verbose_name_plural': 'ایتم های پیش فاکتور'},
        ),
        migrations.AlterUniqueTogether(
            name='quote',
            unique_together={('organization',)},
        ),
        migrations.AlterUniqueTogether(
            name='quoteitem',
            unique_together={('product', 'quote')},
        ),
    ]
