# Generated by Django 3.2.5 on 2021-08-06 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0007_auto_20210805_1043'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='quote',
            unique_together=set(),
        ),
    ]
