# Generated by Django 3.2.5 on 2021-08-11 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0011_auto_20210811_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='slug',
            field=models.SlugField(max_length=20, null=True),
        ),
    ]
