# Generated by Django 3.2.5 on 2021-08-11 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0013_remove_quote_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='slug',
        ),
    ]
