# Generated by Django 3.2.5 on 2021-08-11 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0017_quote_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='name',
        ),
    ]
