# Generated by Django 3.2.5 on 2021-08-13 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0018_remove_quote_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='slug',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
