# Generated by Django 3.2.5 on 2021-07-28 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.SlugField()),
                ('content', models.TextField(max_length=500, verbose_name='متن گزارش کار')),
                ('created_on', models.DateField(auto_now_add=True, verbose_name='تاریخ ثبت گزارش')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organization.organization', verbose_name='یرای سازمان')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پیگیری',
                'verbose_name_plural': ' پیگیری ها',
                'permissions': [],
            },
        ),
    ]
