# Generated by Django 3.2.5 on 2021-08-02 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followup', '0002_emailhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailhistory',
            name='status',
            field=models.CharField(max_length=20, verbose_name='وضعیت ارسال'),
        ),
    ]
