# Generated by Django 3.2.5 on 2021-08-05 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followup', '0004_alter_emailhistory_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailhistory',
            options={'permissions': [], 'verbose_name': 'تاریخجه ارسال ایمیل', 'verbose_name_plural': 'تاریخچه ارسال ایمیل ها'},
        ),
        migrations.RenameField(
            model_name='emailhistory',
            old_name='reciver_addres',
            new_name='receiver',
        ),
        migrations.AlterField(
            model_name='emailhistory',
            name='status',
            field=models.CharField(choices=[('SENT', 'sent'), ('NOT_SENT', 'failed')], max_length=10, verbose_name='وضعیت ارسال'),
        ),
    ]
