# Generated by Django 3.2.5 on 2021-08-09 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('followup', '0005_auto_20210805_1043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followup',
            name='title',
        ),
    ]
