# Generated by Django 3.2.5 on 2021-07-28 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='نام محصول')),
                ('price', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_Includesـtaxes', models.BooleanField(default=False, verbose_name='ایا مشمول مالیات است؟')),
                ('image', models.ImageField(upload_to='', verbose_name='عکس محصول')),
                ('description', models.TextField(help_text='متن نمایشی برای توصیف محصول', verbose_name='توضحیات محصول')),
            ],
            options={
                'verbose_name': 'محصول شرکت ',
                'verbose_name_plural': 'محصولات شزکت',
                'permissions': [],
            },
        ),
        migrations.CreateModel(
            name='OrganizationProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('s_products', models.ManyToManyField(to='products.Product')),
            ],
            options={
                'verbose_name': 'محصول تولیدی سازمان ها ',
                'verbose_name_plural': 'محصولات تولیدی سازمان ها',
                'permissions': [],
            },
        ),
    ]
