# Generated by Django 3.2.5 on 2021-07-30 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdf', verbose_name='کاتالوگ'),
        ),
    ]
